# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mobile-WURFL
version:      0.01
version_from: lib/Mobile/WURFL.pm
installdirs:  site
requires:
    BerkeleyDB:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
